server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        regex: 'anomaly-detector'
        target_label: 'anomaly_detector'
        replacement: 'true'
    pipeline_stages:
      - json:
          expressions:
            message: message
            timestamp: timestamp
            endpoint: endpoint
            method: method
            status_code: status_code
            response_time_ms: response_time_ms
            user_agent: user_agent
            ip_address: ip_address
            request_id: request_id
            suspicious_behavior: suspicious_behavior
            anomaly_score: anomaly_score
      - labels:
          message:
          timestamp:
          endpoint:
          method:
          status_code:
          response_time_ms:
          user_agent:
          ip_address:
          request_id:
          suspicious_behavior:
          anomaly_score:
