global:
  scrape_interval: 15s
  evaluation_interval: 1m

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - /etc/prometheus/rules/anomaly.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'anomaly-app'
    static_configs:
      - targets: ['anomaly-app:5000']
    metrics_path: /api/health
    scrape_interval: 5s

  - job_name: 'blackbox-endpoints'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://anomaly-app:5000/api/users
        - http://anomaly-app:5000/api/products
        - http://anomaly-app:5000/api/orders
        - http://anomaly-app:5000/api/suspicious
        - http://anomaly-app:5000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
